lib/builders/Map-base.js
test/map-builder-test.js

Working to fix some oddities in Input.Map.
showWhen doesn't seem to work in the same way as other controls
locked markers can still be edited with the edit control
locked markers can still be dragged (although the data doesn't update) - this is probably a bug in the QMap
Refactoring as I go, because this is a hella-long method.
There are additional changes to support this in https://github.com/wmfs/quasar-map-mapbox/pull/67

Map Builder fixes

---

lib/builders/Map-base.js

Move from if conditions to lookup was failing when format not specified

fix: Force format to known good value

---

lib/builders/List.js

Story details: https://app.clubhouse.io/wmfs/story/4220

feat: add option to List to show single launches as button rather than menu

---

lib/index.js

Story details: https://app.clubhouse.io/wmfs/story/6927

In Ridge schedule when clicked on find  properties , the page should automatically move to results.

---

lib/builders/TabSet.js

Story details: https://app.shortcut.com/wmfs/story/15715

chore: [sc-15715] Update style of Tabs

---

lib/builders/Action-template.js
lib/builders/ActionSet.js

* allow buttons to have a color attribute (maintaining behaviour with style attribute)
* improve spacing on button dropdown with titles (only add dense attribute if does not have a title)

Action Improvements

---

lib/builders/Image.js

Story details: https://app.shortcut.com/wmfs/story/15869

feat: [sc-15869] New question and Icon for number of storeys

---

lib/builders/Input.ChoiceSet.js

Story details: https://app.shortcut.com/wmfs/story/16265

feat((pin 262) crr dd): [sc-16265] Pre-audit history check form

---

lib/builders/Action-template.js
lib/builders/index.js

Story details: https://app.shortcut.com/wmfs/story/20568

feat((pin 262) crr dd): [sc-20568] Note for Case available to download as PDF (for legal)

---

lib/builders/FactSet.js

Story details: https://app.shortcut.com/wmfs/story/21598

chore: [sc-21598] Add pre-wrap option to FactSet and refactor Read-only view

---

lib/builders/FactSet.js

Story details: https://app.shortcut.com/wmfs/story/21867

feat: [sc-21867] Intervention dashboard

---

lib/builders/Timeline.js
lib/builders/TimelineEntry.js
lib/index.js
lib/utils/apply-launches.js

Story details: https://app.shortcut.com/wmfs/story/22042

feat: [sc-22042] Enable Timeline component to use arrays

---

lib/utils/apply-launches.js

Story details: https://app.shortcut.com/wmfs/story/21447

feat((pin 262) crr dd): [sc-21447] Remove a note

---

lib/builders/Input.Chat.js
lib/builders/index.js

Story details: https://app.shortcut.com/wmfs/story/20986

feat((pin 262) crr dd): [sc-20986] QA Process embeded within FS Audit

---

lib/builders/Input.Chat.js

Story details: https://app.shortcut.com/wmfs/story/23170

feat((pin 262) crr dd): [sc-23170] Add date/time to messages

---

lib/builders/Input.Chat.js

Story details: https://app.shortcut.com/wmfs/story/23169

feat((pin 262) crr dd): [sc-23169] Update comment permissions

---

lib/builders/Input.Chat.js

Story details: https://app.shortcut.com/wmfs/story/23167

feat((pin 262) crr dd): [sc-23167] Visually distinguish messages

---

lib/builders/FactSet.js
lib/builders/Input.ChoiceSet.js

Story details: https://app.shortcut.com/wmfs/story/22966

feat((pin 262) crr dd): [sc-22966] Input.ChoiceSet to store selected choices when using dynamic choices 

---

lib/builders/Text-field.js

Story details: https://app.shortcut.com/wmfs/story/24606

feat((pin 262) crr dd): [sc-24606] Removing of irrelevant question for contact preference

---

lib/builders/List.js
lib/builders/Timeline.js
lib/builders/TimelineEntry.js
test/timeline-entry-test.js

Story details: https://app.shortcut.com/wmfs/story/25751

feat: [sc-25751] Improvements to Timeline component

---

lib/builders/List.js

Story details: https://app.shortcut.com/wmfs/story/21537

feat((pin 262) crr dd): [sc-21537] IEE Calculation Breakdown

---

lib/builders/TabSet.js

Story details: https://app.shortcut.com/wmfs/story/27271

feat((pin 262) crr dd): [sc-27271] Alert to indicate missing fields in all tasks

---

lib/builders/Input.Signature.js

Story details: https://app.shortcut.com/wmfs/story/28563

feat: [sc-28563] Apply error check to Input.Signature

---

lib/builders/Input.Date.js
lib/builders/Input.DateTime.js

Story details: https://app.shortcut.com/wmfs/story/28742

feat((pin 262) crr dd): [sc-28742] Restrict date entry for  'date that the Enforcement Notice must be complied with'

---

lib/builders/Input.Signature.js

Story details: https://app.shortcut.com/wmfs/story/29323

feat((pin 262) crr dd): [sc-29323] Add 'name' input to signature

---

lib/builders/FactSet.js

Story details: https://app.shortcut.com/wmfs/story/29983

feat: [sc-29983] FactSet to allow tooltips

---

lib/utils/apply-tooltip.js

Story details: https://app.shortcut.com/wmfs/story/30007

feat: [sc-30007] Tooltip icons to inherit colour of text

---

lib/builders/CardList.js

Story details: https://app.shortcut.com/wmfs/story/30429

feat: [sc-30429] Extend CardList for options to disable edit/delete

---

lib/builders/Tree.js

Story details: https://app.shortcut.com/wmfs/story/29680

feat((pin 262) crr dd): [sc-29680] Improve Tree Component

---

lib/builders/Input.Chat.js
lib/builders/Text-field.js

Story details: https://app.shortcut.com/wmfs/story/25703

feat((pin 262) crr dd): [sc-25703] Improve display of text-input/messages
